/* =========================================================
   CATÁLOGO DE PRODUTOS

   ESTE FICHEIRO É GERADO. NÃO O EDITES À MÃO.

   Os produtos vêm da folha catalogo/produtos.xlsx. Para mudar o
   catálogo, edita a folha e corre, na pasta do site:

       python3 catalogo/atualizar-site.py

   O que escreveres aqui diretamente é substituído da próxima vez
   que o comando correr.
   ========================================================= */

const PRODUTOS = [
  {
    id: "conde-villar-branco",
    pagina: "conde-villar-branco.html",
    nome: "Conde Villar Branco",
    categoria: "verde",
    tipo: "branco",
    produtor: "Quinta das Arcas",
    regiao: "Vinho Verde DOC",
    ano: null,
    volume: "75 cl",
    alcool: 10.00,
    caixa: 6,
    preco: 2.28,
    descricao: "Loureiro, Arinto, Trajadura e Avesso. Citrinos e um toque tropical, fresco e com uma mineralidade suave. Para marisco, peixe grelhado e saladas.",
    cor: "#C9B35F",
    imagem: "img/produtos/conde-villar-branco.webp"
  },
  {
    id: "arca-nova-vinhao-primoris",
    pagina: "arca-nova-vinhao-primoris.html",
    nome: "Arca Nova Vinhão Primoris",
    categoria: "verde",
    tipo: "tinto",
    produtor: "Quinta das Arcas",
    regiao: "Vinho Verde DOC",
    ano: null,
    volume: "75 cl",
    alcool: 12.00,
    caixa: 6,
    preco: 4.73,
    descricao: "Vinhão feito em lagares tradicionais, uma edição especial da Quinta das Arcas. Cor rubi intensa, ameixa e amoras silvestres bem maduras, estrutura firme e taninos macios. Para carnes vermelhas, enchidos, sarrabulho, lampreia e cabidela.",
    cor: "#53000F",
    imagem: "img/produtos/arca-nova-vinhao-primoris.webp",
    destaque: "Primoris"
  },
  {
    id: "vinho-verde-da-casa",
    pagina: "vinho-verde-da-casa.html",
    nome: "Vinho Verde da Casa",
    categoria: "verde",
    tipo: "branco",
    produtor: "Quinta das Arcas",
    regiao: "Verde",
    ano: null,
    volume: "75 cl",
    alcool: 10.50,
    caixa: 12,
    preco: 2.10,
    descricao: "Vinho verde da casa, o nosso vinho mais vendido.",
    cor: "#C9B35F",
    imagem: "img/produtos/vinho-verde-da-casa.webp"
  },
  {
    id: "piano-colheita-tinto-doc",
    pagina: "piano-colheita-tinto-doc.html",
    nome: "Piano Colheita Tinto DOC",
    categoria: "maduro",
    tipo: "tinto",
    produtor: "Carlos Alonso Douro Wine",
    regiao: "Douro DOC",
    ano: 2025,
    volume: "75 cl",
    alcool: 13.50,
    caixa: 6,
    preco: 3.51,
    descricao: "Touriga Franca e Touriga Nacional, com Tinta Barroca e Tinta Roriz. Frutos vermelhos e ameixa, corpo cheio e taninos macios. Vai bem com carnes, massas cremosas e caça.",
    cor: "#53000F",
    imagem: "img/produtos/piano-colheita-tinto.webp",
    destaque: "DOC"
  },
  {
    id: "piano-branco-doc",
    pagina: "piano-branco-doc.html",
    nome: "Piano Branco DOC",
    categoria: "maduro",
    tipo: "branco",
    produtor: "Carlos Alonso Douro Wine",
    regiao: "Douro DOC",
    ano: null,
    volume: "75 cl",
    caixa: 6,
    preco: 3.51,
    descricao: "Viosinho, Gouveio e Moscatel Galego. Fruta elegante com notas minerais e boa acidez. Para peixe, marisco, saladas ou como aperitivo.",
    cor: "#C9B35F",
    imagem: "img/produtos/piano-colheita-branco.webp",
    destaque: "DOC"
  },
  {
    id: "piano-reserva-tinto",
    pagina: "piano-reserva-tinto.html",
    nome: "Piano Reserva Tinto",
    categoria: "maduro",
    tipo: "tinto",
    produtor: "Carlos Alonso Douro Wine",
    regiao: "Douro DOC",
    ano: null,
    volume: "75 cl",
    alcool: 14.00,
    caixa: 6,
    preco: 5.61,
    descricao: "Tinta Roriz, Touriga Nacional e Touriga Franca, com estágio em barrica. Morango, cassis e ameixa, notas balsâmicas e final longo. Para caça e borrego assado.",
    cor: "#53000F",
    imagem: "img/produtos/piano-reserva-tinto.webp",
    destaque: "Reserva"
  },
  {
    id: "piano-reserva-branco",
    pagina: "piano-reserva-branco.html",
    nome: "Piano Reserva Branco",
    categoria: "maduro",
    tipo: "branco",
    produtor: "Carlos Alonso Douro Wine",
    regiao: "Douro DOC",
    ano: null,
    volume: "75 cl",
    caixa: 6,
    preco: 5.61,
    descricao: "Gouveio, Viosinho e Códega do Larinho, fermentado em barrica de carvalho francês. Fruta madura com toque tropical e tostado, final longo. Para arroz de marisco, peixe grelhado e queijos de pasta mole.",
    cor: "#C9B35F",
    imagem: "img/produtos/piano-reserva-branco.webp",
    destaque: "Reserva"
  },
  {
    id: "piano-17-reserva",
    pagina: "piano-17-reserva.html",
    nome: "Piano 17 Reserva",
    categoria: "maduro",
    tipo: "tinto",
    produtor: "Carlos Alonso Douro Wine",
    regiao: "Douro DOC",
    ano: null,
    volume: "75 cl",
    alcool: 17.00,
    caixa: 6,
    preco: 19.95,
    descricao: "Tinta Roriz, Tinta Barroca e Touriga Franca, com 17% de álcool, 24 meses em barrica e 24 em garrafa. Frutos silvestres, cacau e tabaco, encorpado e envolvente. Para estufados e queijos fortes.",
    cor: "#53000F",
    imagem: "img/produtos/piano-17-reserva.webp",
    destaque: "Reserva"
  },
  {
    id: "piano-vinhas-velhas-premium",
    pagina: "piano-vinhas-velhas-premium.html",
    nome: "Piano Vinhas Velhas Premium",
    categoria: "maduro",
    tipo: "tinto",
    produtor: "Carlos Alonso Douro Wine",
    regiao: "Douro DOC",
    ano: null,
    volume: "75 cl",
    caixa: 6,
    preco: 25.56,
    descricao: "Vinhas velhas do Douro, com 24 meses em barricas novas de carvalho francês. Denso e complexo, de fruta concentrada, mineral e com final longo. Para pratos de caça e assados no forno.",
    cor: "#53000F",
    imagem: "img/produtos/piano-vinhas-velhas-premium.webp",
    destaque: "Premium"
  },
  {
    id: "piano-moscatel-galego-branco",
    pagina: "piano-moscatel-galego-branco.html",
    nome: "Piano Moscatel Galego Branco",
    categoria: "maduro",
    tipo: "branco",
    produtor: "Carlos Alonso Douro Wine",
    regiao: "Douro DOC",
    ano: null,
    volume: "75 cl",
    alcool: 13.00,
    caixa: 6,
    preco: 4.46,
    descricao: "100% Moscatel Galego Branco. Toranja, líchias, lima e fruta tropical, mineral e de frescura viva, com final longo. Para aperitivo, sushi e queijos.",
    cor: "#C9B35F",
    imagem: "img/produtos/piano-moscatel-galego-branco.webp"
  },
  {
    id: "piano-reserva-tinto-magnum",
    pagina: "piano-reserva-tinto-magnum.html",
    nome: "Piano Reserva Tinto Magnum",
    categoria: "maduro",
    tipo: "tinto",
    produtor: "Carlos Alonso Douro Wine",
    regiao: "Douro DOC",
    ano: null,
    volume: "1,5 l",
    alcool: 14.00,
    preco: 21.00,
    descricao: "O Piano Reserva Tinto em garrafa magnum, de 1,5 litros, numa caixa de madeira. Tinta Roriz, Touriga Nacional e Touriga Franca, com morango, cassis e ameixa, notas balsâmicas e final longo. Para caça e borrego assado.",
    cor: "#53000F",
    imagem: "img/produtos/piano-reserva-tinto-magnum.webp",
    destaque: "Magnum"
  },
  {
    id: "piano-grande-reserva-tinto-5-litros",
    pagina: "piano-grande-reserva-tinto-5-litros.html",
    nome: "Piano Grande Reserva Tinto 5 Litros",
    categoria: "maduro",
    tipo: "tinto",
    produtor: "Carlos Alonso Douro Wine",
    regiao: "Douro DOC",
    ano: null,
    volume: "5 l",
    alcool: 14.50,
    preco: 89.25,
    descricao: "O Piano Grande Reserva em garrafa de 5 litros, numa caixa de madeira. Touriga Nacional, Touriga Franca e Tinta Barroca, com estágio em barrica nova. Fruta negra, tabaco e baunilha, taninos firmes e final longo. Para uma festa, com borrego, cabrito ou posta.",
    cor: "#53000F",
    imagem: "img/produtos/piano-grande-reserva-5l.webp",
    destaque: "5 litros"
  },
  {
    id: "quintela-tinto",
    pagina: "quintela-tinto.html",
    nome: "Quintela Tinto",
    categoria: "maduro",
    tipo: "tinto",
    produtor: "Carlos Alonso Douro Wine",
    regiao: "Douro DOC",
    ano: null,
    volume: "75 cl",
    alcool: 13.00,
    caixa: 6,
    preco: 2.89,
    descricao: "Tinta Roriz, Touriga Franca, Tinta Barroca e Touriga Nacional. Notas florais e de compota de frutos vermelhos, com taninos macios. Para carnes brancas, massas e caça.",
    cor: "#53000F",
    imagem: "img/produtos/quintela-tinto.webp"
  },
  {
    id: "quintela-branco",
    pagina: "quintela-branco.html",
    nome: "Quintela Branco",
    categoria: "maduro",
    tipo: "branco",
    produtor: "Carlos Alonso Douro Wine",
    regiao: "Douro DOC",
    ano: null,
    volume: "75 cl",
    caixa: 6,
    preco: 2.89,
    descricao: "Gouveio, Viosinho e Moscatel Galego. Aroma intenso de fruta tropical, fresco e vivo na boca. Para marisco, peixe, carnes brancas e massas.",
    cor: "#C9B35F",
    imagem: "img/produtos/quintela-branco.webp"
  },
  {
    id: "quintela-tinto-37-5-cl",
    pagina: "quintela-tinto-37-5-cl.html",
    nome: "Quintela Tinto 37,5 cl",
    categoria: "maduro",
    tipo: "tinto",
    produtor: "Carlos Alonso Douro Wine",
    regiao: "Douro DOC",
    ano: null,
    volume: "37,5 cl",
    alcool: 13.00,
    caixa: 6,
    preco: 1.63,
    descricao: "A meia garrafa do Quintela Tinto: Tinta Roriz, Touriga Franca, Tinta Barroca e Touriga Nacional, com notas florais e de compota de frutos vermelhos. Boa para uma refeição a dois.",
    cor: "#53000F",
    imagem: "img/produtos/quintela-tinto.webp"
  },
  {
    id: "quintela-branco-37-5-cl",
    pagina: "quintela-branco-37-5-cl.html",
    nome: "Quintela Branco 37,5 cl",
    categoria: "maduro",
    tipo: "branco",
    produtor: "Carlos Alonso Douro Wine",
    regiao: "Douro DOC",
    ano: null,
    volume: "37,5 cl",
    caixa: 6,
    preco: 1.63,
    descricao: "A meia garrafa do Quintela Branco: Gouveio, Viosinho e Moscatel Galego, com fruta tropical e boca fresca. Boa para uma refeição a dois.",
    cor: "#C9B35F",
    imagem: "img/produtos/quintela-branco.webp"
  },
  {
    id: "castello-de-numao-tinto",
    pagina: "castello-de-numao-tinto.html",
    nome: "Castello de Numão Tinto",
    categoria: "maduro",
    tipo: "tinto",
    produtor: "WineWalkers",
    regiao: "Douro DOC",
    ano: null,
    volume: "75 cl",
    alcool: 13.00,
    caixa: 6,
    preco: 3.51,
    descricao: "Tinta Barroca, Tinta Roriz e Touriga Franca. Fruta vermelha, taninos suaves e acidez equilibrada. Um tinto do Douro para o dia a dia, com carnes e pratos de forno.",
    cor: "#53000F",
    imagem: "img/produtos/castello-de-numao-tinto.webp"
  },
  {
    id: "castello-de-numao-branco",
    pagina: "castello-de-numao-branco.html",
    nome: "Castello de Numão Branco",
    categoria: "maduro",
    tipo: "branco",
    produtor: "WineWalkers",
    regiao: "Douro DOC",
    ano: null,
    volume: "75 cl",
    caixa: 6,
    preco: 3.51,
    descricao: "Viosinho, Gouveio e Moscatel. Fruta branca, pera e uva fresca, com notas cítricas e minerais. Para peixe, marisco e saladas.",
    cor: "#C9B35F",
    imagem: "img/produtos/castello-de-numao-branco.webp"
  },
  {
    id: "castello-de-numao-reserva-tinto",
    pagina: "castello-de-numao-reserva-tinto.html",
    nome: "Castello de Numão Reserva Tinto",
    categoria: "maduro",
    tipo: "tinto",
    produtor: "WineWalkers",
    regiao: "Douro DOC",
    ano: null,
    volume: "75 cl",
    alcool: 14.00,
    caixa: 6,
    preco: 7.88,
    descricao: "Tinta Roriz, Touriga Nacional e Touriga Franca, com 12 meses em barrica nova. Cassis, morango e ameixa, taninos de qualidade e final longo. Para caça e cabrito assado.",
    cor: "#53000F",
    imagem: "img/produtos/castello-de-numao-reserva-tinto.webp",
    destaque: "Reserva"
  },
  {
    id: "castello-de-numao-reserva-branco",
    pagina: "castello-de-numao-reserva-branco.html",
    nome: "Castello de Numão Reserva Branco",
    categoria: "maduro",
    tipo: "branco",
    produtor: "WineWalkers",
    regiao: "Douro DOC",
    ano: null,
    volume: "75 cl",
    alcool: 13.50,
    caixa: 6,
    preco: 7.88,
    descricao: "Gouveio, Viosinho e Códega do Larinho, com 9 meses em barrica de carvalho francês. Fruta branca e tropical com um toque tostado, final longo e elegante. Para peixe no forno, marisco e carnes brancas.",
    cor: "#C9B35F",
    imagem: "img/produtos/castello-de-numao-reserva-branco.webp",
    destaque: "Reserva"
  },
  {
    id: "bafarela-reserva-tinto",
    pagina: "bafarela-reserva-tinto.html",
    nome: "Bafarela Reserva Tinto",
    categoria: "maduro",
    tipo: "tinto",
    produtor: "Brites Aguiar",
    regiao: "Douro DOC",
    ano: null,
    volume: "75 cl",
    alcool: 14.00,
    caixa: 6,
    preco: 8.58,
    descricao: "Touriga Nacional, Touriga Franca, Tinta Amarela e Tinta Roriz, com 10 meses em barrica. Fruta vermelha, violeta e especiarias, final fresco e persistente. Para cozinha tradicional, carnes e queijos.",
    cor: "#53000F",
    imagem: "img/produtos/bafarela-reserva-tinto.webp",
    destaque: "Reserva",
    inicio: true
  },
  {
    id: "bafarela-grande-reserva-tinto",
    pagina: "bafarela-grande-reserva-tinto.html",
    nome: "Bafarela Grande Reserva Tinto",
    categoria: "maduro",
    tipo: "tinto",
    produtor: "Brites Aguiar",
    regiao: "Douro DOC",
    ano: null,
    volume: "75 cl",
    alcool: 14.00,
    caixa: 6,
    preco: 13.83,
    descricao: "Touriga Nacional, Touriga Franca e Tinta Roriz, com 12 meses em barrica de carvalho francês. Intenso e floral, de taninos densos mas finos. Para carnes nobres, caça e queijos fortes.",
    cor: "#53000F",
    imagem: "img/produtos/bafarela-grande-reserva-tinto.webp",
    destaque: "Grande Reserva",
    inicio: true
  },
  {
    id: "dom-xisto-tinto",
    pagina: "dom-xisto-tinto.html",
    nome: "Dom Xisto Tinto",
    categoria: "maduro",
    tipo: "tinto",
    produtor: "Adega Dom Xisto",
    regiao: "Douro",
    ano: null,
    volume: "75 cl",
    alcool: 13.00,
    caixa: 6,
    preco: 2.36,
    descricao: "Tinto do Douro feito com castas tradicionais da região, com 13% de álcool. Para o dia a dia, com carnes e petiscos.",
    cor: "#53000F",
    imagem: "img/produtos/dom-xisto.webp"
  },
  {
    id: "dom-xisto-branco",
    pagina: "dom-xisto-branco.html",
    nome: "Dom Xisto Branco",
    categoria: "maduro",
    tipo: "branco",
    produtor: "Adega Dom Xisto",
    regiao: "Douro",
    ano: null,
    volume: "75 cl",
    caixa: 6,
    preco: 2.36,
    descricao: "Branco do Douro feito com castas tradicionais da região. Para o dia a dia, com peixe, saladas e petiscos.",
    cor: "#C9B35F",
    imagem: "img/produtos/dom-xisto.webp"
  },
  {
    id: "tapada-de-villar-tinto",
    pagina: "tapada-de-villar-tinto.html",
    nome: "Tapada de Villar Tinto",
    categoria: "maduro",
    tipo: "tinto",
    produtor: "Quinta das Arcas",
    regiao: "Regional Alentejano",
    ano: null,
    volume: "75 cl",
    alcool: 13.50,
    caixa: 6,
    preco: 2.63,
    descricao: "Alicante Bouschet, Touriga Nacional e Touriga Franca. Cor granada, fruta vermelha intensa, macio e aveludado. Para grelhados e petiscos.",
    cor: "#53000F",
    imagem: "img/produtos/tapada-villar-tinto.webp"
  },
  {
    id: "tapada-de-villar-branco",
    pagina: "tapada-de-villar-branco.html",
    nome: "Tapada de Villar Branco",
    categoria: "maduro",
    tipo: "branco",
    produtor: "Quinta das Arcas",
    regiao: "Regional Alentejano",
    ano: null,
    volume: "75 cl",
    alcool: 12.50,
    caixa: 6,
    preco: 2.63,
    descricao: "Roupeiro, Antão Vaz e Chardonnay. Frutado com um toque floral, seco mas redondo, de acidez viva. Para peixe, saladas e petiscos.",
    cor: "#C9B35F",
    imagem: "img/produtos/tapada-villar-branco.webp"
  },
  {
    id: "tapada-de-villar-doc-tinto",
    pagina: "tapada-de-villar-doc-tinto.html",
    nome: "Tapada de Villar DOC Tinto",
    categoria: "maduro",
    tipo: "tinto",
    produtor: "Quinta das Arcas",
    regiao: "Alentejo DOC",
    ano: null,
    volume: "75 cl",
    alcool: 14.00,
    caixa: 6,
    preco: 3.68,
    descricao: "Alicante Bouschet, Touriga Nacional e Syrah. Especiarias e frutos vermelhos maduros, taninos macios e final elegante. Para carnes vermelhas e assados.",
    cor: "#53000F",
    imagem: "img/produtos/tapada-villar-doc-tinto.webp",
    destaque: "DOC"
  },
  {
    id: "tapada-de-villar-doc-branco",
    pagina: "tapada-de-villar-doc-branco.html",
    nome: "Tapada de Villar DOC Branco",
    categoria: "maduro",
    tipo: "branco",
    produtor: "Quinta das Arcas",
    regiao: "Alentejo DOC",
    ano: null,
    volume: "75 cl",
    alcool: 13.50,
    caixa: 6,
    preco: 3.68,
    descricao: "Roupeiro e Arinto, com parte do vinho fermentada em barrica de carvalho francês. Fruta e flores, volume na boca, mineral e de final fresco. Para peixe no forno, bacalhau e carnes brancas.",
    cor: "#C9B35F",
    imagem: "img/produtos/tapada-villar-doc-branco.webp",
    destaque: "DOC"
  },
  {
    id: "porto-piano-tawny",
    pagina: "porto-piano-tawny.html",
    nome: "Porto Piano Tawny",
    categoria: "porto",
    tipo: "tawny",
    produtor: "Carlos Alonso Douro Wine",
    regiao: "Douro",
    ano: null,
    volume: "75 cl",
    alcool: 19.00,
    preco: 8.19,
    descricao: "Tinta Roriz, Tinta Barroca, Touriga Nacional e Touriga Franca, envelhecido em madeira de carvalho. Especiarias e frutos secos, elegante, de doçura equilibrada e final persistente. Para sobremesas de caramelo ou café, tarte de maçã e queijos fortes.",
    cor: "#8A4B1C",
    imagem: "img/produtos/porto-piano-tawny.webp"
  },
  {
    id: "porto-piano-10-anos",
    pagina: "porto-piano-10-anos.html",
    nome: "Porto Piano 10 Anos",
    categoria: "porto",
    tipo: "tawny",
    produtor: "Carlos Alonso Douro Wine",
    regiao: "Douro",
    ano: null,
    volume: "75 cl",
    alcool: 19.00,
    preco: 18.38,
    descricao: "Um tawny de 10 anos, envelhecido em madeira, de Tinta Roriz, Touriga Franca, Tinta Barroca e Touriga Nacional. Notas florais e de fruta madura, especiarias e frutos secos, corpo equilibrado e final longo. Para leite-creme, tartes de fruta, frutos secos e queijos azuis.",
    cor: "#8A4B1C",
    imagem: "img/produtos/porto-piano-10-anos.webp",
    destaque: "10 Anos"
  },
  {
    id: "quinta-da-mata-fidalga-branco-bruto",
    pagina: "quinta-da-mata-fidalga-branco-bruto.html",
    nome: "Quinta da Mata Fidalga Branco Bruto",
    categoria: "espumantes",
    tipo: "branco",
    docura: "Bruto",
    produtor: "Quinta da Mata Fidalga",
    regiao: "Bairrada",
    ano: null,
    volume: "75 cl",
    caixa: 6,
    preco: 7.00,
    descricao: "Maria Gomes, Baga, Arinto e Chardonnay. Citrinos, pera, ananás e pêssego, com bolha fina e boa persistência. Para aperitivo, marisco e leitão.",
    cor: "#DCC98A",
    imagem: "img/produtos/mata-fidalga-branco-bruto.webp"
  },
  {
    id: "quinta-da-mata-fidalga-tinto-bruto",
    pagina: "quinta-da-mata-fidalga-tinto-bruto.html",
    nome: "Quinta da Mata Fidalga Tinto Bruto",
    categoria: "espumantes",
    tipo: "tinto",
    docura: "Bruto",
    produtor: "Quinta da Mata Fidalga",
    regiao: "Bairrada",
    ano: null,
    volume: "75 cl",
    alcool: 12.70,
    caixa: 6,
    preco: 7.00,
    descricao: "Baga e Touriga Nacional, pelo método clássico, com nove meses de estágio. Cor rubi, fruta e notas vegetais, bolha fina. Para leitão, enchidos e carnes assadas.",
    cor: "#53000F",
    imagem: "img/produtos/mata-fidalga-tinto-bruto.webp"
  },
  {
    id: "quinta-da-mata-fidalga-rose-bruto",
    pagina: "quinta-da-mata-fidalga-rose-bruto.html",
    nome: "Quinta da Mata Fidalga Rosé Bruto",
    categoria: "espumantes",
    tipo: "rosé",
    docura: "Bruto",
    produtor: "Quinta da Mata Fidalga",
    regiao: "Bairrada",
    ano: null,
    volume: "75 cl",
    caixa: 6,
    preco: 7.00,
    descricao: "Baga e Touriga Nacional, pelo método clássico. Cor rosa definida, bolha fina e aroma intenso de frutos vermelhos frescos, com ataque suave. Para aperitivo, marisco e pratos leves.",
    cor: "#D98A9A",
    imagem: "img/produtos/mata-fidalga-rose-bruto.webp"
  },
  {
    id: "fraga-da-pena-bruto",
    pagina: "fraga-da-pena-bruto.html",
    nome: "Fraga da Pena Bruto",
    categoria: "espumantes",
    tipo: "branco",
    docura: "Bruto",
    produtor: "Caves Terras do Demo",
    regiao: "Távora-Varosa",
    ano: null,
    volume: "75 cl",
    alcool: 12.50,
    caixa: 3,
    preco: 9.98,
    descricao: "Malvasia Fina, Verdelho e Folgasão, pelo método clássico. Floral e muito fresco, com notas de fermento e pão torrado. Para aperitivo, marisco e peixe.",
    cor: "#DCC98A",
    imagem: "img/produtos/fraga-da-pena-bruto.webp"
  },
  {
    id: "murganheira-reserva-bruto",
    pagina: "murganheira-reserva-bruto.html",
    nome: "Murganheira Reserva Bruto",
    categoria: "espumantes",
    tipo: "branco",
    docura: "Bruto",
    produtor: "Caves da Murganheira",
    regiao: "Távora-Varosa",
    ano: null,
    volume: "75 cl",
    alcool: 12.50,
    caixa: 3,
    preco: 11.03,
    descricao: "Malvasia Fina, Cerceal, Gouveio Real e Touriga Franca, pelo método clássico. Aroma de frutos secos, fresco e equilibrado, de bolha fina. Para celebrar, com marisco ou peixe.",
    cor: "#DCC98A",
    imagem: "img/produtos/murganheira-reserva-bruto.webp",
    destaque: "Reserva"
  },
  {
    id: "murganheira-super-reserva-bruto",
    pagina: "murganheira-super-reserva-bruto.html",
    nome: "Murganheira Super Reserva Bruto",
    categoria: "espumantes",
    tipo: "branco",
    docura: "Bruto",
    produtor: "Caves da Murganheira",
    regiao: "Távora-Varosa",
    ano: null,
    volume: "75 cl",
    alcool: 12.50,
    caixa: 3,
    preco: 13.13,
    descricao: "Malvasia Fina, Cerceal e Tinta Roriz, pelo método clássico. Aroma harmonioso com notas de baunilha, final longo e equilibrado. Para peixe grelhado e marisco.",
    cor: "#DCC98A",
    imagem: "img/produtos/murganheira-super-reserva-bruto.webp",
    destaque: "Super Reserva"
  },
  {
    id: "terras-do-demo-branco-bruto",
    pagina: "terras-do-demo-branco-bruto.html",
    nome: "Terras do Demo Branco Bruto",
    categoria: "espumantes",
    tipo: "branco",
    docura: "Bruto",
    produtor: "Caves Terras do Demo",
    regiao: "Távora-Varosa",
    ano: null,
    volume: "75 cl",
    alcool: 12.00,
    caixa: 3,
    preco: 9.28,
    descricao: "Malvasia Fina, pelo método clássico, com mais de 12 meses de estágio. Aroma de flor de malvasia, fresco e frutado, bolha fina e persistente. Para marisco, ostras, peixe e aves.",
    cor: "#DCC98A",
    imagem: "img/produtos/terras-do-demo-bruto.webp"
  },
  {
    id: "terras-do-demo-rose-bruto",
    pagina: "terras-do-demo-rose-bruto.html",
    nome: "Terras do Demo Rosé Bruto",
    categoria: "espumantes",
    tipo: "rosé",
    docura: "Bruto",
    produtor: "Caves Terras do Demo",
    regiao: "Távora-Varosa",
    ano: null,
    volume: "75 cl",
    alcool: 12.50,
    caixa: 3,
    preco: 9.28,
    descricao: "Touriga Nacional. Cor salmão, morango fresco e um toque floral, com acidez viva e corpo leve. Para massas, marisco grelhado e carnes brancas.",
    cor: "#D98A9A",
    imagem: "img/produtos/terras-do-demo-rose-bruto.webp"
  },
  {
    id: "terras-do-demo-tinto-bruto",
    pagina: "terras-do-demo-tinto-bruto.html",
    nome: "Terras do Demo Tinto Bruto",
    categoria: "espumantes",
    tipo: "tinto",
    docura: "Bruto",
    produtor: "Caves Terras do Demo",
    regiao: "Távora-Varosa",
    ano: null,
    volume: "75 cl",
    alcool: 12.00,
    caixa: 3,
    preco: 9.28,
    descricao: "Touriga Franca, pelo método clássico. Tons violáceos, rosa e amora, com notas de levedura e pão torrado. Para leitão, cabrito e carnes assadas.",
    cor: "#53000F",
    imagem: "img/produtos/terras-do-demo-tinto-bruto.webp"
  },
  {
    id: "conde-villar-bruto-reserva",
    pagina: "conde-villar-bruto-reserva.html",
    nome: "Conde Villar Bruto Reserva",
    categoria: "espumantes",
    tipo: "branco",
    docura: "Bruto",
    produtor: "Quinta das Arcas",
    regiao: "",
    ano: null,
    volume: "75 cl",
    alcool: 12.00,
    caixa: 3,
    preco: 6.30,
    descricao: "Blanc de noirs de Baga, feito pelo método clássico. Bolha fina e persistente, notas de maçã e biscoito, acidez viva. Para aperitivo e pratos de peixe.",
    cor: "#DCC98A",
    imagem: "img/produtos/conde-villar-bruto-reserva.webp",
    destaque: "Reserva"
  },
  {
    id: "piano-espumante-bruto",
    pagina: "piano-espumante-bruto.html",
    nome: "Piano Espumante Bruto",
    categoria: "espumantes",
    tipo: "branco",
    docura: "Bruto",
    produtor: "Carlos Alonso Douro Wine",
    regiao: "Douro",
    ano: null,
    volume: "75 cl",
    alcool: 12.00,
    caixa: 3,
    preco: 5.60,
    descricao: "Gouveio, Malvasia Fina e Moscatel Galego, pelo método clássico. Floral e fresco, com fruta verde e um toque de pão torrado, cremoso na boca. Para aperitivo, entradas e peixe.",
    cor: "#DCC98A",
    imagem: "img/produtos/piano-espumante-bruto.webp"
  },
  {
    id: "raposeira-reserva-bruto",
    pagina: "raposeira-reserva-bruto.html",
    nome: "Raposeira Reserva Bruto",
    categoria: "espumantes",
    tipo: "branco",
    docura: "Bruto",
    produtor: "Caves da Raposeira",
    regiao: "Távora-Varosa",
    ano: null,
    volume: "75 cl",
    caixa: 3,
    preco: 7.88,
    descricao: "O espumante clássico de Lamego, feito pelo método clássico. Equilibrado, fino e de acidez viva. Para aperitivo, peixe e marisco.",
    cor: "#DCC98A",
    imagem: "img/produtos/raposeira-reserva-bruto.webp",
    destaque: "Reserva"
  },
  {
    id: "raposeira-reserva-meio-seco",
    pagina: "raposeira-reserva-meio-seco.html",
    nome: "Raposeira Reserva Meio Seco",
    categoria: "espumantes",
    tipo: "branco",
    docura: "Meio Seco",
    produtor: "Caves da Raposeira",
    regiao: "Távora-Varosa",
    ano: null,
    volume: "75 cl",
    caixa: 3,
    preco: 7.88,
    descricao: "O espumante clássico de Lamego, pelo método clássico, num estilo meio seco. Cor palha, aroma fresco e frutado, boca suave. Para sobremesas, bolos e para brindar.",
    cor: "#DCC98A",
    imagem: "img/produtos/raposeira-reserva-meio-seco.webp",
    destaque: "Reserva"
  },
  {
    id: "raposeira-reserva-doce",
    pagina: "raposeira-reserva-doce.html",
    nome: "Raposeira Reserva Doce",
    categoria: "espumantes",
    tipo: "branco",
    docura: "Doce",
    produtor: "Caves da Raposeira",
    regiao: "Távora-Varosa",
    ano: null,
    volume: "75 cl",
    caixa: 3,
    preco: 7.88,
    descricao: "O espumante clássico de Lamego, pelo método clássico, na versão doce. Aroma fresco e frutado, boca macia. Para bolos, doces e para brindar.",
    cor: "#DCC98A",
    imagem: "img/produtos/raposeira-reserva-doce.webp",
    destaque: "Reserva"
  },
  {
    id: "3-monts-75-cl",
    pagina: "3-monts-75-cl.html",
    nome: "3 Monts 75 cl",
    categoria: "cervejas",
    tipo: "cerveja",
    produtor: "Brasserie 3 Monts",
    regiao: "Flandres, França",
    ano: null,
    volume: "75 cl",
    alcool: 8.50,
    caixa: 6,
    preco: 3.94,
    descricao: "Bière de garde loura da Flandres francesa, com 8,5% de álcool. Aromas de fruta, coentro e lúpulo, e final seco. Vai bem com francesinha e queijos.",
    cor: "#C08A2E",
    imagem: "img/produtos/3-monts-75cl.webp"
  },
  {
    id: "3-monts-33-cl",
    pagina: "3-monts-33-cl.html",
    nome: "3 Monts 33 cl",
    categoria: "cervejas",
    tipo: "cerveja",
    produtor: "Brasserie 3 Monts",
    regiao: "Flandres, França",
    ano: null,
    volume: "33 cl",
    alcool: 8.50,
    caixa: 12,
    preco: 2.28,
    descricao: "A mesma bière de garde loura da Flandres francesa, em garrafa pequena. 8,5% de álcool, aromas de fruta, coentro e lúpulo.",
    cor: "#C08A2E",
    imagem: "img/produtos/3-monts-33cl.webp"
  },
  {
    id: "3-monts-heritage-cereales",
    pagina: "3-monts-heritage-cereales.html",
    nome: "3 Monts Héritage Céréales",
    categoria: "cervejas",
    tipo: "cerveja",
    produtor: "Brasserie 3 Monts",
    regiao: "Flandres, França",
    ano: null,
    volume: "75 cl",
    alcool: 9.00,
    caixa: 6,
    preco: 5.95,
    descricao: "Tripla loura de 9%, feita com cereais antigos: cevada, aveia, espelta e trigo. Doce de cereal, amargor leve e notas de fruta madura e especiarias.",
    cor: "#C08A2E",
    imagem: "img/produtos/3-monts-heritage-cereales.webp"
  },
  {
    id: "3-monts-triple-grande-reserve",
    pagina: "3-monts-triple-grande-reserve.html",
    nome: "3 Monts Triple Grande Réserve",
    categoria: "cervejas",
    tipo: "cerveja",
    produtor: "Brasserie 3 Monts",
    regiao: "Flandres, França",
    ano: null,
    volume: "75 cl",
    alcool: 9.50,
    caixa: 6,
    preco: 4.38,
    descricao: "Tripla de 9,5%, feita com duas leveduras. Dourada, com aromas de banana madura, fruta de caroço e pão fresco, notas de caramelo e baunilha e um amargor longo. Para grelhados, pato e queijos curados.",
    cor: "#C08A2E",
    imagem: "img/produtos/3-monts-triple-grande-reserve.webp",
    destaque: "Reserva"
  },
  {
    id: "la-divine",
    pagina: "la-divine.html",
    nome: "La Divine",
    categoria: "cervejas",
    tipo: "cerveja",
    produtor: "Saint-Landelin (Brasserie Goudale)",
    regiao: "Norte de França",
    ano: null,
    volume: "75 cl",
    alcool: 8.50,
    caixa: 6,
    preco: 4.12,
    descricao: "Loura de guarda do norte de França, com 8,5% de álcool. Aromas de fruta, madeira e caramelo suave, com um amargor leve e persistente.",
    cor: "#C08A2E",
    imagem: "img/produtos/la-divine.webp"
  }
];

/* Nomes bonitos para mostrar no site, por categoria */
const CATEGORIAS = {
  verde:      { nome: "Verde",      descricao: "Noroeste atlântico. Leves, cítricos e de acidez marcada." },
  maduro:     { nome: "Maduro",     descricao: "Do Douro e do Alentejo, tintos e brancos para todas as ocasiões." },
  porto:      { nome: "Porto",      descricao: "Vinho do Porto, para a sobremesa, os queijos e o fim da refeição." },
  espumantes: { nome: "Espumantes", descricao: "Método clássico e bolha fina, para celebrar ou acompanhar a refeição." },
  cervejas:   { nome: "Cervejas",   descricao: "Cervejas especiais, para beber devagar e à mesa." }
};
