/* =========================================================
   CATÁLOGO DE PRODUTOS

   ESTE FICHEIRO É GERADO. NÃO O EDITES À MÃO.

   Os produtos vêm da folha catalogo/produtos.xlsx. Para mudar o
   catálogo, edita a folha e corre, na pasta do site:

       python3 catalogo/atualizar-site.py

   O que escreveres aqui diretamente é substituído da próxima vez
   que o comando correr.
   ========================================================= */

const PRODUTOS = [
  {
    id: "conde-villar-branco",
    nome: "Conde Villar Branco",
    categoria: "verde",
    tipo: "branco",
    produtor: "Quinta das Arcas",
    regiao: "Vinho Verde DOC",
    ano: null,
    volume: "75 cl",
    preco: 3.95,
    descricao: "Loureiro, Arinto, Trajadura e Avesso. Citrinos e um toque tropical, fresco e com uma mineralidade suave. Para marisco, peixe grelhado e saladas.",
    cor: "#C9B35F",
    imagem: "img/produtos/conde-villar-branco.webp"
  },
  {
    id: "arca-nova-vinhao-primoris",
    nome: "Arca Nova Vinhão Primoris",
    categoria: "verde",
    tipo: "tinto",
    produtor: "Quinta das Arcas",
    regiao: "Vinho Verde DOC",
    ano: null,
    volume: "75 cl",
    preco: 7.50,
    descricao: "Vinhão feito em lagares tradicionais, uma edição especial da Quinta das Arcas. Cor rubi intensa, ameixa e amoras silvestres bem maduras, estrutura firme e taninos macios. Para carnes vermelhas, enchidos, sarrabulho, lampreia e cabidela.",
    cor: "#53000F",
    imagem: "img/produtos/arca-nova-vinhao-primoris.webp"
  },
  {
    id: "piano-colheita-tinto",
    nome: "Piano Colheita Tinto",
    categoria: "maduro",
    tipo: "tinto",
    produtor: "Carlos Alonso Douro Wine",
    regiao: "Douro DOC",
    ano: 2025,
    volume: "75 cl",
    preco: 4.95,
    descricao: "Touriga Franca e Touriga Nacional, com Tinta Barroca e Tinta Roriz. Frutos vermelhos e ameixa, corpo cheio e taninos macios. Vai bem com carnes, massas cremosas e caça.",
    cor: "#53000F",
    imagem: "img/produtos/piano-colheita-tinto.webp"
  },
  {
    id: "piano-colheita-branco",
    nome: "Piano Colheita Branco",
    categoria: "maduro",
    tipo: "branco",
    produtor: "Carlos Alonso Douro Wine",
    regiao: "Douro DOC",
    ano: null,
    volume: "75 cl",
    preco: 4.95,
    descricao: "Viosinho, Gouveio e Moscatel Galego. Fruta elegante com notas minerais e boa acidez. Para peixe, marisco, saladas ou como aperitivo.",
    cor: "#C9B35F",
    imagem: "img/produtos/piano-colheita-branco.webp"
  },
  {
    id: "piano-reserva-tinto",
    nome: "Piano Reserva Tinto",
    categoria: "maduro",
    tipo: "tinto",
    produtor: "Carlos Alonso Douro Wine",
    regiao: "Douro DOC",
    ano: null,
    volume: "75 cl",
    preco: 7.50,
    descricao: "Tinta Roriz, Touriga Nacional e Touriga Franca, com estágio em barrica. Morango, cassis e ameixa, notas balsâmicas e final longo. Para caça e borrego assado.",
    cor: "#53000F",
    imagem: "img/produtos/piano-reserva-tinto.webp",
    destaque: "Reserva"
  },
  {
    id: "piano-reserva-branco",
    nome: "Piano Reserva Branco",
    categoria: "maduro",
    tipo: "branco",
    produtor: "Carlos Alonso Douro Wine",
    regiao: "Douro DOC",
    ano: null,
    volume: "75 cl",
    preco: 7.95,
    descricao: "Gouveio, Viosinho e Códega do Larinho, fermentado em barrica de carvalho francês. Fruta madura com toque tropical e tostado, final longo. Para arroz de marisco, peixe grelhado e queijos de pasta mole.",
    cor: "#C9B35F",
    imagem: "img/produtos/piano-reserva-branco.webp",
    destaque: "Reserva"
  },
  {
    id: "piano-17-reserva",
    nome: "Piano 17 Reserva",
    categoria: "maduro",
    tipo: "tinto",
    produtor: "Carlos Alonso Douro Wine",
    regiao: "Douro DOC",
    ano: null,
    volume: "75 cl",
    preco: 26.50,
    descricao: "Tinta Roriz, Tinta Barroca e Touriga Franca, com 17% de álcool, 24 meses em barrica e 24 em garrafa. Frutos silvestres, cacau e tabaco, encorpado e envolvente. Para estufados e queijos fortes.",
    cor: "#53000F",
    imagem: "img/produtos/piano-17-reserva.webp"
  },
  {
    id: "piano-vinhas-velhas-premium",
    nome: "Piano Vinhas Velhas Premium",
    categoria: "maduro",
    tipo: "tinto",
    produtor: "Carlos Alonso Douro Wine",
    regiao: "Douro DOC",
    ano: null,
    volume: "75 cl",
    preco: 27.50,
    descricao: "Vinhas velhas do Douro, com 24 meses em barricas novas de carvalho francês. Denso e complexo, de fruta concentrada, mineral e com final longo. Para pratos de caça e assados no forno.",
    cor: "#53000F",
    imagem: "img/produtos/piano-vinhas-velhas-premium.webp"
  },
  {
    id: "quintela-tinto",
    nome: "Quintela Tinto",
    categoria: "maduro",
    tipo: "tinto",
    produtor: "Carlos Alonso Douro Wine",
    regiao: "Douro DOC",
    ano: null,
    volume: "75 cl",
    preco: 4.50,
    descricao: "Tinta Roriz, Touriga Franca, Tinta Barroca e Touriga Nacional. Notas florais e de compota de frutos vermelhos, com taninos macios. Para carnes brancas, massas e caça.",
    cor: "#53000F",
    imagem: "img/produtos/quintela-tinto.webp"
  },
  {
    id: "quintela-branco",
    nome: "Quintela Branco",
    categoria: "maduro",
    tipo: "branco",
    produtor: "Carlos Alonso Douro Wine",
    regiao: "Douro DOC",
    ano: null,
    volume: "75 cl",
    preco: 4.50,
    descricao: "Gouveio, Viosinho e Moscatel Galego. Aroma intenso de fruta tropical, fresco e vivo na boca. Para marisco, peixe, carnes brancas e massas.",
    cor: "#C9B35F",
    imagem: "img/produtos/quintela-branco.webp"
  },
  {
    id: "quintela-tinto-37-5-cl",
    nome: "Quintela Tinto 37,5 cl",
    categoria: "maduro",
    tipo: "tinto",
    produtor: "Carlos Alonso Douro Wine",
    regiao: "Douro DOC",
    ano: null,
    volume: "37,5 cl",
    preco: 2.95,
    descricao: "A meia garrafa do Quintela Tinto: Tinta Roriz, Touriga Franca, Tinta Barroca e Touriga Nacional, com notas florais e de compota de frutos vermelhos. Boa para uma refeição a dois.",
    cor: "#53000F",
    imagem: "img/produtos/quintela-tinto.webp"
  },
  {
    id: "quintela-branco-37-5-cl",
    nome: "Quintela Branco 37,5 cl",
    categoria: "maduro",
    tipo: "branco",
    produtor: "Carlos Alonso Douro Wine",
    regiao: "Douro DOC",
    ano: null,
    volume: "37,5 cl",
    preco: 2.95,
    descricao: "A meia garrafa do Quintela Branco: Gouveio, Viosinho e Moscatel Galego, com fruta tropical e boca fresca. Boa para uma refeição a dois.",
    cor: "#C9B35F",
    imagem: "img/produtos/quintela-branco.webp"
  },
  {
    id: "castello-de-numao-tinto",
    nome: "Castello de Numão Tinto",
    categoria: "maduro",
    tipo: "tinto",
    produtor: "WineWalkers",
    regiao: "Douro DOC",
    ano: null,
    volume: "75 cl",
    preco: 3.95,
    descricao: "Tinta Barroca, Tinta Roriz e Touriga Franca. Fruta vermelha, taninos suaves e acidez equilibrada. Um tinto do Douro para o dia a dia, com carnes e pratos de forno.",
    cor: "#53000F",
    imagem: "img/produtos/castello-de-numao-tinto.webp"
  },
  {
    id: "castello-de-numao-branco",
    nome: "Castello de Numão Branco",
    categoria: "maduro",
    tipo: "branco",
    produtor: "WineWalkers",
    regiao: "Douro DOC",
    ano: null,
    volume: "75 cl",
    preco: 3.50,
    descricao: "Viosinho, Gouveio e Moscatel. Fruta branca, pera e uva fresca, com notas cítricas e minerais. Para peixe, marisco e saladas.",
    cor: "#C9B35F",
    imagem: "img/produtos/castello-de-numao-branco.webp"
  },
  {
    id: "castello-de-numao-reserva-tinto",
    nome: "Castello de Numão Reserva Tinto",
    categoria: "maduro",
    tipo: "tinto",
    produtor: "WineWalkers",
    regiao: "Douro DOC",
    ano: null,
    volume: "75 cl",
    preco: 6.95,
    descricao: "Tinta Roriz, Touriga Nacional e Touriga Franca, com 12 meses em barrica nova. Cassis, morango e ameixa, taninos de qualidade e final longo. Para caça e cabrito assado.",
    cor: "#53000F",
    imagem: "img/produtos/castello-de-numao-reserva-tinto.webp"
  },
  {
    id: "castello-de-numao-reserva-branco",
    nome: "Castello de Numão Reserva Branco",
    categoria: "maduro",
    tipo: "branco",
    produtor: "WineWalkers",
    regiao: "Douro DOC",
    ano: null,
    volume: "75 cl",
    preco: 8.95,
    descricao: "Gouveio, Viosinho e Códega do Larinho, com 9 meses em barrica de carvalho francês. Fruta branca e tropical com um toque tostado, final longo e elegante. Para peixe no forno, marisco e carnes brancas.",
    cor: "#C9B35F",
    imagem: "img/produtos/castello-de-numao-reserva-branco.webp"
  },
  {
    id: "bafarela-reserva-tinto",
    nome: "Bafarela Reserva Tinto",
    categoria: "maduro",
    tipo: "tinto",
    produtor: "Brites Aguiar",
    regiao: "Douro DOC",
    ano: null,
    volume: "75 cl",
    preco: 7.50,
    descricao: "Touriga Nacional, Touriga Franca, Tinta Amarela e Tinta Roriz, com 10 meses em barrica. Fruta vermelha, violeta e especiarias, final fresco e persistente. Para cozinha tradicional, carnes e queijos.",
    cor: "#53000F",
    imagem: "img/produtos/bafarela-reserva-tinto.webp"
  },
  {
    id: "bafarela-grande-reserva-tinto",
    nome: "Bafarela Grande Reserva Tinto",
    categoria: "maduro",
    tipo: "tinto",
    produtor: "Brites Aguiar",
    regiao: "Douro DOC",
    ano: null,
    volume: "75 cl",
    preco: 14.95,
    descricao: "Touriga Nacional, Touriga Franca e Tinta Roriz, com 12 meses em barrica de carvalho francês. Intenso e floral, de taninos densos mas finos. Para carnes nobres, caça e queijos fortes.",
    cor: "#53000F",
    imagem: "img/produtos/bafarela-grande-reserva-tinto.webp"
  },
  {
    id: "dom-xisto-tinto",
    nome: "Dom Xisto Tinto",
    categoria: "maduro",
    tipo: "tinto",
    produtor: "Adega Dom Xisto",
    regiao: "Douro",
    ano: null,
    volume: "75 cl",
    preco: 3.50,
    descricao: "Tinto do Douro feito com castas tradicionais da região, com 13% de álcool. Para o dia a dia, com carnes e petiscos.",
    cor: "#53000F",
    imagem: "img/produtos/dom-xisto.webp"
  },
  {
    id: "dom-xisto-branco",
    nome: "Dom Xisto Branco",
    categoria: "maduro",
    tipo: "branco",
    produtor: "Adega Dom Xisto",
    regiao: "Douro",
    ano: null,
    volume: "75 cl",
    preco: 3.50,
    descricao: "Branco do Douro feito com castas tradicionais da região. Para o dia a dia, com peixe, saladas e petiscos.",
    cor: "#C9B35F",
    imagem: "img/produtos/dom-xisto.webp"
  },
  {
    id: "tapada-villar-tinto",
    nome: "Tapada Villar Tinto",
    categoria: "maduro",
    tipo: "tinto",
    produtor: "Quinta das Arcas",
    regiao: "Regional Alentejano",
    ano: null,
    volume: "75 cl",
    preco: 4.25,
    descricao: "Alicante Bouschet, Touriga Nacional e Touriga Franca. Cor granada, fruta vermelha intensa, macio e aveludado. Para grelhados e petiscos.",
    cor: "#53000F",
    imagem: "img/produtos/tapada-villar-tinto.webp"
  },
  {
    id: "tapada-villar-branco",
    nome: "Tapada Villar Branco",
    categoria: "maduro",
    tipo: "branco",
    produtor: "Quinta das Arcas",
    regiao: "Regional Alentejano",
    ano: null,
    volume: "75 cl",
    preco: 4.25,
    descricao: "Roupeiro, Antão Vaz e Chardonnay. Frutado com um toque floral, seco mas redondo, de acidez viva. Para peixe, saladas e petiscos.",
    cor: "#C9B35F",
    imagem: "img/produtos/tapada-villar-branco.webp"
  },
  {
    id: "tapada-villar-doc-tinto",
    nome: "Tapada Villar DOC Tinto",
    categoria: "maduro",
    tipo: "tinto",
    produtor: "Quinta das Arcas",
    regiao: "Alentejo DOC",
    ano: null,
    volume: "75 cl",
    preco: 6.25,
    descricao: "Alicante Bouschet, Touriga Nacional e Syrah. Especiarias e frutos vermelhos maduros, taninos macios e final elegante. Para carnes vermelhas e assados.",
    cor: "#53000F",
    imagem: "img/produtos/tapada-villar-doc-tinto.webp"
  },
  {
    id: "quinta-da-mata-fidalga-branco-bruto",
    nome: "Quinta da Mata Fidalga Branco Bruto",
    categoria: "espumantes",
    tipo: "branco",
    docura: "Bruto",
    produtor: "Quinta da Mata Fidalga",
    regiao: "Bairrada",
    ano: null,
    volume: "75 cl",
    preco: 8.50,
    descricao: "Maria Gomes, Baga, Arinto e Chardonnay. Citrinos, pera, ananás e pêssego, com bolha fina e boa persistência. Para aperitivo, marisco e leitão.",
    cor: "#DCC98A",
    imagem: "img/produtos/mata-fidalga-branco-bruto.webp"
  },
  {
    id: "quinta-da-mata-fidalga-tinto-bruto",
    nome: "Quinta da Mata Fidalga Tinto Bruto",
    categoria: "espumantes",
    tipo: "tinto",
    docura: "Bruto",
    produtor: "Quinta da Mata Fidalga",
    regiao: "Bairrada",
    ano: null,
    volume: "75 cl",
    preco: 9.50,
    descricao: "Baga e Touriga Nacional, pelo método clássico, com nove meses de estágio. Cor rubi, fruta e notas vegetais, bolha fina. Para leitão, enchidos e carnes assadas.",
    cor: "#53000F",
    imagem: "img/produtos/mata-fidalga-tinto-bruto.webp"
  },
  {
    id: "quinta-da-mata-fidalga-rose-bruto",
    nome: "Quinta da Mata Fidalga Rosé Bruto",
    categoria: "espumantes",
    tipo: "rosé",
    docura: "Bruto",
    produtor: "Quinta da Mata Fidalga",
    regiao: "Bairrada",
    ano: null,
    volume: "75 cl",
    preco: 8.95,
    descricao: "Baga e Touriga Nacional, pelo método clássico. Cor rosa definida, bolha fina e aroma intenso de frutos vermelhos frescos, com ataque suave. Para aperitivo, marisco e pratos leves.",
    cor: "#D98A9A",
    imagem: "img/produtos/mata-fidalga-rose-bruto.webp"
  },
  {
    id: "fraga-da-pena-bruto",
    nome: "Fraga da Pena Bruto",
    categoria: "espumantes",
    tipo: "branco",
    docura: "Bruto",
    produtor: "Caves Terras do Demo",
    regiao: "Távora-Varosa",
    ano: null,
    volume: "75 cl",
    preco: 10.95,
    descricao: "Malvasia Fina, Verdelho e Folgasão, pelo método clássico. Floral e muito fresco, com notas de fermento e pão torrado. Para aperitivo, marisco e peixe.",
    cor: "#DCC98A",
    imagem: "img/produtos/fraga-da-pena-bruto.webp"
  },
  {
    id: "murganheira-reserva-bruto",
    nome: "Murganheira Reserva Bruto",
    categoria: "espumantes",
    tipo: "branco",
    docura: "Bruto",
    produtor: "Caves da Murganheira",
    regiao: "Távora-Varosa",
    ano: null,
    volume: "75 cl",
    preco: 11.95,
    descricao: "Malvasia Fina, Cerceal, Gouveio Real e Touriga Franca, pelo método clássico. Aroma de frutos secos, fresco e equilibrado, de bolha fina. Para celebrar, com marisco ou peixe.",
    cor: "#DCC98A",
    imagem: "img/produtos/murganheira-reserva-bruto.webp",
    destaque: "Reserva"
  },
  {
    id: "murganheira-super-reserva-bruto",
    nome: "Murganheira Super Reserva Bruto",
    categoria: "espumantes",
    tipo: "branco",
    docura: "Bruto",
    produtor: "Caves da Murganheira",
    regiao: "Távora-Varosa",
    ano: null,
    volume: "75 cl",
    preco: 14.50,
    descricao: "Malvasia Fina, Cerceal e Tinta Roriz, pelo método clássico. Aroma harmonioso com notas de baunilha, final longo e equilibrado. Para peixe grelhado e marisco.",
    cor: "#DCC98A",
    imagem: "img/produtos/murganheira-super-reserva-bruto.webp"
  },
  {
    id: "terras-do-demo-bruto",
    nome: "Terras do Demo Bruto",
    categoria: "espumantes",
    tipo: "branco",
    docura: "Bruto",
    produtor: "Caves Terras do Demo",
    regiao: "Távora-Varosa",
    ano: null,
    volume: "75 cl",
    preco: 9.95,
    descricao: "Malvasia Fina, pelo método clássico, com mais de 12 meses de estágio. Aroma de flor de malvasia, fresco e frutado, bolha fina e persistente. Para marisco, ostras, peixe e aves.",
    cor: "#DCC98A",
    imagem: "img/produtos/terras-do-demo-bruto.webp"
  },
  {
    id: "terras-do-demo-rose-bruto",
    nome: "Terras do Demo Rosé Bruto",
    categoria: "espumantes",
    tipo: "rosé",
    docura: "Bruto",
    produtor: "Caves Terras do Demo",
    regiao: "Távora-Varosa",
    ano: null,
    volume: "75 cl",
    preco: 9.95,
    descricao: "Touriga Nacional. Cor salmão, morango fresco e um toque floral, com acidez viva e corpo leve. Para massas, marisco grelhado e carnes brancas.",
    cor: "#D98A9A",
    imagem: "img/produtos/terras-do-demo-rose-bruto.webp"
  },
  {
    id: "terras-do-demo-tinto-bruto",
    nome: "Terras do Demo Tinto Bruto",
    categoria: "espumantes",
    tipo: "tinto",
    docura: "Bruto",
    produtor: "Caves Terras do Demo",
    regiao: "Távora-Varosa",
    ano: null,
    volume: "75 cl",
    preco: 9.95,
    descricao: "Touriga Franca, pelo método clássico. Tons violáceos, rosa e amora, com notas de levedura e pão torrado. Para leitão, cabrito e carnes assadas.",
    cor: "#53000F",
    imagem: "img/produtos/terras-do-demo-tinto-bruto.webp"
  },
  {
    id: "conde-villar-bruto-reserva",
    nome: "Conde Villar Bruto Reserva",
    categoria: "espumantes",
    tipo: "branco",
    docura: "Bruto",
    produtor: "Quinta das Arcas",
    regiao: "",
    ano: null,
    volume: "75 cl",
    preco: 9.50,
    descricao: "Blanc de noirs de Baga, feito pelo método clássico. Bolha fina e persistente, notas de maçã e biscoito, acidez viva. Para aperitivo e pratos de peixe.",
    cor: "#DCC98A",
    imagem: "img/produtos/conde-villar-bruto-reserva.webp",
    destaque: "Reserva"
  },
  {
    id: "piano-espumante-bruto",
    nome: "Piano Espumante Bruto",
    categoria: "espumantes",
    tipo: "branco",
    docura: "Bruto",
    produtor: "Carlos Alonso Douro Wine",
    regiao: "Douro",
    ano: null,
    volume: "75 cl",
    preco: 6.50,
    descricao: "Gouveio, Malvasia Fina e Moscatel Galego, pelo método clássico. Floral e fresco, com fruta verde e um toque de pão torrado, cremoso na boca. Para aperitivo, entradas e peixe.",
    cor: "#DCC98A",
    imagem: "img/produtos/piano-espumante-bruto.webp"
  },
  {
    id: "raposeira-reserva-bruto",
    nome: "Raposeira Reserva Bruto",
    categoria: "espumantes",
    tipo: "branco",
    docura: "Bruto",
    produtor: "Caves da Raposeira",
    regiao: "Távora-Varosa",
    ano: null,
    volume: "75 cl",
    preco: 8.75,
    descricao: "O espumante clássico de Lamego, feito pelo método clássico. Equilibrado, fino e de acidez viva. Para aperitivo, peixe e marisco.",
    cor: "#DCC98A",
    imagem: "img/produtos/raposeira-reserva-bruto.webp"
  },
  {
    id: "raposeira-reserva-meio-seco",
    nome: "Raposeira Reserva Meio Seco",
    categoria: "espumantes",
    tipo: "branco",
    docura: "Meio Seco",
    produtor: "Caves da Raposeira",
    regiao: "Távora-Varosa",
    ano: null,
    volume: "75 cl",
    preco: 8.75,
    descricao: "O espumante clássico de Lamego, pelo método clássico, num estilo meio seco. Cor palha, aroma fresco e frutado, boca suave. Para sobremesas, bolos e para brindar.",
    cor: "#DCC98A",
    imagem: "img/produtos/raposeira-reserva-meio-seco.webp"
  },
  {
    id: "raposeira-reserva-doce",
    nome: "Raposeira Reserva Doce",
    categoria: "espumantes",
    tipo: "branco",
    docura: "Doce",
    produtor: "Caves da Raposeira",
    regiao: "Távora-Varosa",
    ano: null,
    volume: "75 cl",
    preco: 8.75,
    descricao: "O espumante clássico de Lamego, pelo método clássico, na versão doce. Aroma fresco e frutado, boca macia. Para bolos, doces e para brindar.",
    cor: "#DCC98A",
    imagem: "img/produtos/raposeira-reserva-doce.webp"
  },
  {
    id: "3-monts-75-cl",
    nome: "3 Monts 75 cl",
    categoria: "cervejas",
    tipo: "cerveja",
    produtor: "Brasserie 3 Monts",
    regiao: "Flandres, França",
    ano: null,
    volume: "75 cl",
    preco: 7.50,
    descricao: "Bière de garde loura da Flandres francesa, com 8,5% de álcool. Aromas de fruta, coentro e lúpulo, e final seco. Vai bem com francesinha e queijos.",
    cor: "#C08A2E",
    imagem: "img/produtos/3-monts-75cl.webp"
  },
  {
    id: "3-monts-33-cl",
    nome: "3 Monts 33 cl",
    categoria: "cervejas",
    tipo: "cerveja",
    produtor: "Brasserie 3 Monts",
    regiao: "Flandres, França",
    ano: null,
    volume: "33 cl",
    preco: 2.95,
    descricao: "A mesma bière de garde loura da Flandres francesa, em garrafa pequena. 8,5% de álcool, aromas de fruta, coentro e lúpulo.",
    cor: "#C08A2E",
    imagem: "img/produtos/3-monts-33cl.webp"
  },
  {
    id: "3-monts-heritage-cereales",
    nome: "3 Monts Héritage Céréales",
    categoria: "cervejas",
    tipo: "cerveja",
    produtor: "Brasserie 3 Monts",
    regiao: "Flandres, França",
    ano: null,
    volume: "75 cl",
    preco: 8.90,
    descricao: "Tripla loura de 9%, feita com cereais antigos: cevada, aveia, espelta e trigo. Doce de cereal, amargor leve e notas de fruta madura e especiarias.",
    cor: "#C08A2E",
    imagem: "img/produtos/3-monts-heritage-cereales.webp"
  },
  {
    id: "3-monts-triple-grande-reserve",
    nome: "3 Monts Triple Grande Réserve",
    categoria: "cervejas",
    tipo: "cerveja",
    produtor: "Brasserie 3 Monts",
    regiao: "Flandres, França",
    ano: null,
    volume: "75 cl",
    preco: 6.95,
    descricao: "Tripla de 9,5%, feita com duas leveduras. Dourada, com aromas de banana madura, fruta de caroço e pão fresco, notas de caramelo e baunilha e um amargor longo. Para grelhados, pato e queijos curados.",
    cor: "#C08A2E",
    imagem: "img/produtos/3-monts-triple-grande-reserve.webp"
  },
  {
    id: "la-divine",
    nome: "La Divine",
    categoria: "cervejas",
    tipo: "cerveja",
    produtor: "Saint-Landelin (Brasserie Goudale)",
    regiao: "Norte de França",
    ano: null,
    volume: "75 cl",
    preco: 5.50,
    descricao: "Loura de guarda do norte de França, com 8,5% de álcool. Aromas de fruta, madeira e caramelo suave, com um amargor leve e persistente.",
    cor: "#C08A2E",
    imagem: "img/produtos/la-divine.webp"
  }
];

/* Nomes bonitos para mostrar no site, por categoria */
const CATEGORIAS = {
  verde:      { nome: "Verde",      descricao: "Noroeste atlântico. Leves, cítricos e de acidez marcada." },
  maduro:     { nome: "Maduro",     descricao: "Do Douro e do Alentejo, tintos e brancos para todas as ocasiões." },
  espumantes: { nome: "Espumantes", descricao: "Método clássico e bolha fina, para celebrar ou acompanhar a refeição." },
  cervejas:   { nome: "Cervejas",   descricao: "Cervejas especiais, para beber devagar e à mesa." }
};
